criticalstack/libevhtp

- evhtp.c
- evhtp.h
as per issue#6, try to steady those socket leaks as well as we can for now.
> issue#6: fix various potential socket leaks.

- evhtp.c
- evhtp.h
- examples/test.c
- examples/test_perf.c
Most of these are used internally only - but if not - use the following functions now:
`evhtp_(enable|disable)_flag` : `EVHTP_FLAG_ENABLE_100_CONT`, `EVHTP_FLAG_ENABLE_REUSEPORT`. `EVHTP_FLAG_ENABLE_NODELAY`. `EVHTP_FLAG_ENABLE_DEFER_ACCEPT`, `EVHTP_FLAG_DEFAULTS`
`evhtp_connection_(enable|disable)_flag`:  `EVHTP_CONN_FLAG_ERROR`, `EVHTP_CONN_FLAG_OWNER`, `EVHTP_CONN_FLAG_VHOST_VIA_SNI`, `EVHTP_CONN_FLAG_PAUSED`. `EVHTP_CONN_FLAG_CONNECTED`, `EVHTP_CONN_FLAG_WAITING`, `EVHTP_CONN_FLAG_FREE_CONN`. `EVHTP_CONN_FLAG_KEEPALIVE`
`evhtp_request_(enable|disable)_flag`: `EVHTP_REQ_FLAG_KEEPALIVE`, `EVHTP_REQ_FLAG_FINISHED`, `EVHTP_REQ_FLAG_CHUNKED`, `EVHTP_REQ_FLAG_ERROR`
> Use bitflags instead of bitfields for various configs/settings/states

- evhtp.c
- evhtp.h
- evhtp_json.c
- examples/test.c
#10
Let this burn in until the all-clear is given by users.
- Created the following functions which replace `evhtp_set_hook()`
* evhtp_connection_set_hook()
* evhtp_request_set_hook()
* evhtp_callback_set_hook()
These have the same params as set_hook aside from the specific data
type.
This is part of the effort of un-exposing all of the (internal)
structures.
> Internalize some structs / deprecate evhtp_set_hook()

- evhtp.c
- evhtp.h
add a callback member in evhtp_ssl_cfg_t struct for customized decryption of private file.
fixes #16
> fixes #16 add a callback member in evhtp_ssl_cfg_t struct

- evhtp.h
attribute deprecated should be together with the declaration that is deprecated and not separated by `;`
> Fix deprecated usage

- thread.c
This regression was introduced in b6340022fcec.
> Fix typo in `evthr_new()` function name

- evhtp.c
Fix build on SunOS (Solaris and illumos distributions like SmartOS, OpenIndiana, ...) by not using the reserved `sun` word.
> fix build on SunOS

- evhtp.c
- previously htp__callback_find_()'s strncmp() for type_hash
would use the path_len instead of the callbacks path length
This is wrong: if you have a callback set for '/foo/', and you
request '/', the evaluation was: strncmp("/foo/", "/", 1);
Which will, of course, match "/foo/" since it's only looking
for one byte.
Instead, it should be: strncmp("/", "/foo/", 5) which would
not take the true branch.
- evhtp_callback_new now correctly sets the length (which is now
used in htp__callback_find_
> [Bugfix #51] htp__callback_find_ length check fix

- evhtp.c
Check connection->type to ensure that it is not evhtp_type_client. Also checked for c->htp to not be null in a couple of ssl related functions.
> Likely defect fix for issue #42. 

- CMakeLists.txt
`set_target_properties` is missing an argument name for setting
SOVERSION, resulting in a build error when configuring:
```
CMake Error at CMakeLists.txt:199 (set_target_properties):
set_target_properties called with incorrect number of arguments.
```
> Fix compilation with shared libraries

- CMakeLists.txt
- cmake/options.cmake
- examples/CMakeLists.txt
- examples/https/README.md
- examples/https/example_https.c
- include/evhtp/config.h.in
- include/evhtp/sslutils.h
- sslutils.c
The SSL utility API consists of various functions that make life easier when it comes to dealing with native SSL objects and converting them into other formats. A good example of this can be found in `examples/https/example_https.c` in the function `ssl__add_x_headers_()`
A quick run-down example, appending `X-` headers to the HTTP response for SSL'y type information:
```C
unsigned char * subj_str = NULL;
unsigned char * issr_str = NULL;
unsigned char * nbf_str  = NULL;
unsigned char * naf_str  = NULL;
unsigned char * ser_str  = NULL;
unsigned char * cip_str  = NULL;
unsigned char * sha1_str = NULL;
unsigned char * cert_str = NULL;
if ((subj_str = htp_sslutil_subject_tostr(ssl))) {
evhtp_headers_add_header(
headers,
evhtp_header_new("X-SSL-Subject", subj_str, 0, 1));
}
if ((issr_str = …
```
> New SSL Utility API

- parser.c
As reported via https://github.com/criticalstack/libevhtp/issues/69,
there is a slight chance that 1 byte can overflow parser->buf[STACK_MAX]
when adding the extra '\0'
Added the macro `HTP_SET_BUF(CH)` which does proper bounds checks before
writing the final '\0'.
> [#69] Fix potential out of bound write to p->buf

- parser.c
While the API was never effected by this, I guess a user who had set
their own parser error could have triggered this read. But alas, a bug
is a bug.
We don't look for error + 1 in the error string table, we just look for
error > last_enum.
> [#72] Fix for oob read from htparser_get_strerror

- thread.c
The evthr struct references `exit_cb` of type `evthr_init_cb`.
The `evthr_init_cb` is a typedef to `void (*)(evthr_t *, void *)`
Both of these typedefs are of the same attributes, so nothing bad
happens here; it's more about readability. This patch simply changes
the value type definition of `exit_cb` to the aliased type
`evthr_exit_cb`.
Nothing changes, nothing was "broken", but we need to be consistent.
> [resolves #76] consistent member type definitions of struct evthr

- evhtp.c
- examples/CMakeLists.txt
- examples/eutils.h
- examples/example_basic.c
- examples/example_locality.c
- include/evhtp/evhtp.h
* anything that was returning a numerical value (i.e., 500) now uses the proper `EVHTP_RES_XX` definition.
* Lowered the span of lines for alignment. That was just getting insane.
* continued lines for a function call are aligned 4 spaces in, not at the open bracket.
* Added various debug logs / error logs statements.
* Fixes #90, which I don't know if it was really a bug, just a misuse. When freeing key/value's, when you allocate one, `0` means do not allocate a copy, `1` means create a copy of the data, but the free function only checks for non zero values. The fix was to simply check for specifically '1' to determine if it is free'able.
**note** we may want to turn this into a boolean.
* Added new function `htp__serv_setsockopts_` which makes sure all the proper listener sockopts are …
> This patch "fixes" issue #90, sockopt refactor, and minor fixes.

- examples/example_basic.c
- parser.c
As the issue states, the user result of `hook_body_run` is not checked for error before checking `content_len`. This fixes that.
> [#95] Fixes ignored return for s_body_read in parser.c

- evhtp.c
As reported by @mawenbao - content-length should not be added if the
content-type is chunked.
> [#108] do not include content-length with chunked

- evhtp.c
Without having a way to report the length of the unescaped string, there is
no way to unescape a blob that contains nul.  This change modifies out to be
one character past the end of the unescaped string, allowing for
unsigned char * escaped = ...;
size_t escaped_l = strlen(escaped);
unsigned char * unescaped[escaped_l+1];
size_t unescaped_l = 0;
unsigned char * c = unescaped;
if (0==evhtp_unescape_string(&c, escaped, escaped_l))
unescaped_l = c - unescaped;
It might be better to just return the unescaped length but some callers
might already rely on !evhtp_unescape_string indicating successful
unescaping.  If it turns out that more callers already rely on out not
changing, that's a better solution but it might be wise to just add a v2
function and have the original call it instead. …
> [unescape_string] allow out to report unescaped length

- evhtp.c
CRYPTO_set_id_callback was deprecated in 1.0.2, which breaks the build
if deprecated APIs are disabled at compile time.
> Switch to using OpenSSL's thread API for 1.0.2

- evhtp.c
- include/evhtp/evhtp.h
- sslutils.c
All threading APIs are gone with 1.1.
dh.h header does not get included with ssl.h automatically when deprecated
APIs are disabled.
X509_getBefore/After were replaced with get0 and getm variants. Switched
to the former as it can be const.
> Fix compilation without deprecated OpenSSL 1.1 APIs
